workflow:
  id: { WORKFLOW_ID }
  name: { WORKFLOW_DISPLAY_NAME }
  description: >-
    {WORKFLOW_DESCRIPTION_LINE_1}
    {WORKFLOW_DESCRIPTION_LINE_2}

  agents:
    - .claude/agents/{ AGENT_1_CATEGORY }/{ AGENT_1 }.md
    - .claude/agents/{ AGENT_2_CATEGORY }/{ AGENT_2 }.md  
    - .claude/agents/shared/{ AGENT_3 }.md

  steps:
    - id: { STEP_1_ID }
      title: { STEP_1_TITLE }
      agent: .claude/agents/{ STEP_1_AGENT_CATEGORY }/{ STEP_1_AGENT }.md
      uses: { STEP_1_TEMPLATE }
      requires: { STEP_1_REQUIRES }
      creates: { STEP_1_CREATES }

    - id: { STEP_2_ID }
      title: { STEP_2_TITLE }
      agent: .claude/agents/{ STEP_2_AGENT_CATEGORY }/{ STEP_2_AGENT }.md
      requires: { STEP_2_REQUIRES }
      creates: { STEP_2_CREATES }

    - id: { STEP_3_ID }
      title: { STEP_3_TITLE }
      agent: .claude/agents/{ STEP_3_AGENT_CATEGORY }/{ STEP_3_AGENT }.md
      requires:
        - { STEP_3_REQUIRES_1 }
        - { STEP_3_REQUIRES_2 }
      creates: { STEP_3_CREATES }

handoff_prompts:
  { AGENT_1_TO_AGENT_2 }: '{ HANDOFF_PROMPT_1 }'
  { AGENT_2_TO_AGENT_3 }: '{ HANDOFF_PROMPT_2 }'
  { WORKFLOW_COMPLETION }: '{ COMPLETION_PROMPT }'
</file>
